# Generated by Django 5.1.4 on 2024-12-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_group_alter_category_options_alter_publication_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
