# Generated by Django 5.1.4 on 2025-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_publication_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники группы'},
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='role',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='instrument',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='biography',
            field=models.TextField(default='Биография пока не указана', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='photo',
            field=models.ImageField(default='default_photo_url_or_path', upload_to='group_members', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
